name: Deploy to Azure Web App development slot as a Linux web app.
on:
  push:
    branches: [ "dev" ]
  workflow_dispatch:

env:
  AZURE_WEBAPP_NAME: journee-webportal    
  NODE_VERSION: '18.x'                

permissions:
  contents: read

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3

    - name: Set up Node.js
      uses: actions/setup-node@v3
      with:
        node-version: ${{ env.NODE_VERSION }}
        cache: 'npm'

    - name: Configure .env.production
      run: |
        echo "REACT_APP_API_URL=${{ secrets.REACT_APP_API_URL_DEV }}" > .env.production

    - name: npm install, build
      run: |
        npm install
        CI=false npm run build

    - name: Zip build files for upload between jobs
      run: zip --symlinks -r react.zip ./build

    - name: Upload artifact for deployment job
      uses: actions/upload-artifact@v3
      with:
        name: node-app
        path: react.zip

  deploy:
    permissions:
      contents: none
    runs-on: ubuntu-latest
    needs: build
    environment:
      name: 'Development'
      url: ${{ steps.deploy-to-webapp.outputs.webapp-url }}

    steps:
    - name: Download artifact from build job
      uses: actions/download-artifact@v3
      with:
        name: node-app

    - name: 'Deploy to Azure WebApp'
      id: deploy-to-webapp
      uses: azure/webapps-deploy@v2
      with:
        app-name: ${{ env.AZURE_WEBAPP_NAME }}
        publish-profile: ${{ secrets.AZURE_WEBAPP_PUBLISH_PROFILE_DEVELOP }}
        package: react.zip